apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: admin
spec:
  project: default
  source:
    path: apps
    repoURL: https://github.com/IgorWalkowiak/home-cluster.git
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true