apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: admin
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: cert-manager
    targetRevision: 1.3.23
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true