apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
  namespace: admin
spec:
  project: default
  source:
    repoURL: https://github.com/IgorWalkowiak/home-cluster
    targetRevision: master
    path: manifests/cluster-issuer
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
