apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent-operator
  namespace: admin
spec:
  project: default
  source:
    repoURL: oci://packages.confluent.io/helm
    chart: confluent-for-kubernetes
    targetRevision: 0.1145.6
  destination:
    server: https://kubernetes.default.svc
    namespace: confluent
  syncPolicy:
    automated:
      prune: true