apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent-operator
  namespace: admin
spec:
  project: default
  source:
    repoURL: confluentinc
    chart: confluent-for-kubernetes
    targetRevision: 2.10.0
  destination:
    server: https://kubernetes.default.svc
    namespace: confluent
  syncPolicy:
    automated:
      prune: true