apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: admin
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.47.16
    helm:
      values: |
        kind: DaemonSet
        
        image:
          repository: fluent/fluent-bit
          tag: "3.2.2"
          pullPolicy: IfNotPresent
        
        env:
          - name: FLUENT_ELASTICSEARCH_HOST
            value: "loki"
          - name: FLUENT_ELASTICSEARCH_PORT
            value: "3100"
        
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        
        tolerations:
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        
        nodeSelector: {}
        
        affinity: {}
        
        serviceAccount:
          create: true
          annotations: {}
          name: fluent-bit
        
        rbac:
          create: true
          nodeAccess: true
        
        podSecurityContext:
          fsGroup: 2000
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
        
        service:
          type: ClusterIP
          port: 2020
          labels: {}
          annotations: {}
        
        serviceMonitor:
          enabled: true
          namespace: monitoring
          interval: 30s
          scrapeTimeout: 10s
          selector: {}
        
        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush {{ .Values.flush }}
                Log_Level {{ .Values.logLevel }}
                Parsers_File /fluent-bit/etc/parsers.conf
                Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port {{ .Values.metricsPort }}
                Health_Check On
                storage.path /tmp/flb-storage/
                storage.sync normal
                storage.checksum off
                storage.backlog.mem_limit 100MB
          
          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*.log
                multiline.parser docker, cri
                Tag kube.*
                Mem_Buf_Limit 50MB
                Skip_Long_Lines On
                storage.type filesystem
                
            [INPUT]
                Name systemd
                Tag host.*
                Systemd_Filter _SYSTEMD_UNIT=kubelet.service
                Read_From_Tail On
                storage.type filesystem
          
          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Kube_URL https://kubernetes.default.svc:443
                Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
                Kube_Tag_Prefix kube.var.log.containers.
                Merge_Log On
                Merge_Log_Key log_processed
                K8S-Logging.Parser On
                K8S-Logging.Exclude Off
                Labels On
                Annotations On
                Use_Kubelet On
                Kubelet_Port 10250
                Buffer_Size 0
                
            [FILTER]
                Name nest
                Match kube.*
                Operation lift
                Nested_under kubernetes
                Add_prefix kubernetes_
                
            [FILTER]
                Name modify
                Match kube.*
                Copy kubernetes_pod_name pod
                Copy kubernetes_namespace_name namespace
                Copy kubernetes_container_name container
                Remove time
                Remove kubernetes_pod_id
                Remove kubernetes_docker_id
                Remove kubernetes_container_hash
          
          outputs: |
            [OUTPUT]
                Name loki
                Match kube.*
                Host loki.admin.svc.cluster.local
                Port 3100
                Labels job=fluent-bit,namespace=$kubernetes_namespace_name,pod=$kubernetes_pod_name,container=$kubernetes_container_name
                Label_keys $kubernetes_labels
                Remove_keys kubernetes_labels
                Line_format json
                Auto_kubernetes_labels on
                
            [OUTPUT]
                Name loki
                Match host.*
                Host loki.admin.svc.cluster.local
                Port 3100
                Labels job=fluent-bit,hostname=$HOSTNAME
                Line_format json
          
          customParsers: |
            [PARSER]
                Name docker_no_time
                Format json
                Time_Keep Off
                Time_Key time
                Time_Format %Y-%m-%dT%H:%M:%S.%L
                
            [PARSER]
                Name containerd
                Format regex
                Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
                Time_Key    time
                Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        
        volumeMounts:
          - name: config
            mountPath: /fluent-bit/etc/conf
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: etcmachineid
            mountPath: /etc/machine-id
            readOnly: true
          - name: flb-storage
            mountPath: /tmp/flb-storage
        
        volumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
          - name: etcmachineid
            hostPath:
              path: /etc/machine-id
              type: File
          - name: flb-storage
            emptyDir: {}
        
        flush: 1
        logLevel: info
        metricsPort: 2020
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 