apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: admin
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.47.16
    helm:
      values: |
        kind: DaemonSet
        
        image:
          repository: fluent/fluent-bit
          tag: "3.2.2"
          pullPolicy: IfNotPresent
        
        env: []
        
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        
        tolerations:
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        
        nodeSelector: {}
        
        affinity: {}
        
        serviceAccount:
          create: true
        
        rbac:
          create: true
        
        podSecurityContext:
          fsGroup: 2000
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
        
        service:
          type: ClusterIP
          port: 2020
        
        serviceMonitor:
          enabled: false
        
        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush {{ .Values.flush }}
                Log_Level {{ .Values.logLevel }}
                Parsers_File /fluent-bit/etc/parsers.conf
                Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port {{ .Values.metricsPort }}
                Health_Check On
                storage.path /tmp/flb-storage/
                storage.sync normal
                storage.checksum off
                storage.backlog.mem_limit 100MB
          
          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*.log
                multiline.parser docker, cri
                Tag kube.*
                Mem_Buf_Limit 50MB
                Skip_Long_Lines On
          
          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Kube_URL https://kubernetes.default.svc:443
                Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
                Merge_Log On
                Keep_Log Off
                K8S-Logging.Parser On
                K8S-Logging.Exclude Off
          
          outputs: |
            [OUTPUT]
                Name loki
                Match *
                Host loki.admin.svc.cluster.local
                Port 3100
                Labels job=fluent-bit
                Auto_kubernetes_labels on
          
          customParsers: |
            [PARSER]
                Name docker_no_time
                Format json
                Time_Keep Off
                Time_Key time
                Time_Format %Y-%m-%dT%H:%M:%S.%L
                
            [PARSER]
                Name containerd
                Format regex
                Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
                Time_Key    time
                Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        
        volumeMounts:
          - name: config
            mountPath: /fluent-bit/etc/conf
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: etcmachineid
            mountPath: /etc/machine-id
            readOnly: true
          - name: flb-storage
            mountPath: /tmp/flb-storage
        
        volumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
          - name: etcmachineid
            hostPath:
              path: /etc/machine-id
              type: File
          - name: flb-storage
            emptyDir: {}
        
        flush: 1
        logLevel: info
        metricsPort: 2020
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 