apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: admin
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: fluent-bit
    targetRevision: 3.1.5
    helm:
      values: |
        config:
          flush: 1
          logLevel: info
          service: |
            [SERVICE]
                Flush        {{ .Values.config.flush }}
                Daemon       Off
                Log_Level    {{ .Values.config.logLevel }}
                Config_Watch On
                HTTP_Server  On
                HTTP_Listen  0.0.0.0
                HTTP_Port    {{ .Values.containerPorts.http }}
                Parsers_File /opt/bitnami/fluent-bit/conf/parsers.conf
                Parsers_File /opt/bitnami/fluent-bit/conf/custom_parsers.conf
          inputs: |
            [INPUT]
                Name              tail
                Path              /var/log/containers/*.log
                multiline.parser  docker, cri
                Tag               kube.*
                Mem_Buf_Limit     50MB
                Skip_Long_Lines   On
          filters: |
            [FILTER]
                Name                kubernetes
                Match               kube.*
                Kube_URL            https://kubernetes.default.svc:443
                Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
                Kube_Tag_Prefix     kube.var.log.containers.
                Merge_Log           On
                Keep_Log            Off
                K8S-Logging.Parser  On
                K8S-Logging.Exclude Off
                Annotations         On
                Labels              On
          outputs: |
            [OUTPUT]
                Name              loki
                Match             *
                Host              loki-grafana-loki-query-frontend.admin.svc.cluster.local
                Port              3100
                Labels            job=fluent-bit
          extraFiles:
            labelmap.conf: |
              kubernetes_pod_name pod
              kubernetes_namespace_name namespace
              kubernetes_container_name container
        rbac:
          create: true
          nodeAccess: true
        serviceAccount:
          create: true
        daemonset:
          enabled: true
        tolerations:
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        volumeMounts:
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
        volumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 