apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: admin
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: grafana
    targetRevision: 11.6.6
    helm:
      values: |
        global:
          storageClass: smb-sc
        
        admin:
          password: "admin123"
        
        persistence:
          enabled: true
          size: 5Gi
          storageClass: smb-sc
        
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        
        # Podstawowa konfiguracja datasource dla Loki
        datasources:
          secretDefinition:
            apiVersion: 1
            datasources:
            - name: Loki
              type: loki
              access: proxy
              url: http://loki.admin.svc.cluster.local:3100
              isDefault: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
type: Opaque
data:
  admin-user: YWRtaW4=  # admin
  admin-password: YWRtaW4xMjM=  # admin123 