apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: admin
data:
  grafana.ini: |
    [server]
    domain = grafana.local
    root_url = https://grafana.local
    
    [analytics]
    check_for_updates = false
    check_for_plugin_updates = false
    
    [security]
    disable_gravatar = true
    
    [users]
    viewers_can_edit = false
    editors_can_admin = false
    
    [auth]
    disable_login_form = false
    
    [auth.anonymous]
    enabled = false
    
    [log]
    mode = console
    level = info
    
    [alerting]
    enabled = true
    
    [feature_toggles]
    enable = logsSampleInExplore
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: admin
type: Opaque
data:
  admin-password: UGFzc3dvcmQxMjM= # Password123 w base64
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  namespace: admin
type: Opaque
stringData:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.admin.svc.cluster.local:3100
      version: 1
      isDefault: true
      jsonData:
        maxLines: 1000
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus.monitoring.svc.cluster.local:9090
      isDefault: false
      jsonData:
        timeInterval: 30s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: admin
data:
  kubernetes-logs.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Kubernetes Logs Analysis",
        "tags": ["kubernetes", "logs"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Log Volume Over Time",
            "type": "timeseries",
            "targets": [
              {
                "expr": "sum(rate({job=\"fluent-bit\"}[5m])) by (namespace)",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "logs/sec"
              }
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Recent Logs",
            "type": "logs",
            "targets": [
              {
                "expr": "{job=\"fluent-bit\"} |= \"\"",
                "refId": "A"
              }
            ],
            "options": {
              "showTime": true,
              "showLabels": true,
              "wrapLogMessage": false,
              "enableLogDetails": true,
              "sortOrder": "Descending"
            },
            "gridPos": {
              "h": 16,
              "w": 24,
              "x": 0,
              "y": 8
            }
          },
          {
            "id": 3,
            "title": "Error Logs",
            "type": "logs",
            "targets": [
              {
                "expr": "{job=\"fluent-bit\"} |~ \"(?i)(error|exception|fail|fatal)\"",
                "refId": "A"
              }
            ],
            "options": {
              "showTime": true,
              "showLabels": true,
              "wrapLogMessage": false,
              "enableLogDetails": true,
              "sortOrder": "Descending"
            },
            "gridPos": {
              "h": 12,
              "w": 24,
              "x": 0,
              "y": 24
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "timepicker": {},
        "templating": {
          "list": [
            {
              "name": "namespace",
              "type": "query",
              "query": "label_values({job=\"fluent-bit\"}, namespace)",
              "current": {
                "value": "All",
                "text": "All"
              },
              "includeAll": true,
              "allValue": ".*"
            }
          ]
        },
        "annotations": {
          "list": []
        },
        "refresh": "5s",
        "schemaVersion": 16,
        "version": 1
      }
    } 