apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-resources
  namespace: admin
spec:
  project: default
  source:
    repoURL: https://github.com/user/home-cluster.git  # Tutaj wstaw właściwą ścieżkę do repozytorium
    path: apps/manifests/grafana
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 