apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: admin
spec:
  project: default
  source:
    repoURL: http://pajikos.github.io/home-assistant-helm-chart
    chart: home-assistant
    targetRevision: 1.35.0
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
