apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: admin
spec:
  project: default
  source:
    repoURL: http://pajikos.github.io/home-assistant-helm-chart
    chart: home-assistant
    targetRevision: 0.2.100
    helm:
      values: |
        service:
          type: ClusterIP
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.tls.certresolver: "duckdnsresolver"
          hosts:
            - host: ha.iwal.duckdns.org
              paths: 
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
              - ha.iwal.duckdns.org
              secretName: home-assistant-cert
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
