apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: admin
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: kafka
    targetRevision: 31.2.0
    helm:
      values: |
        listeners:
          clients:
            protocol: PLAINTEXT
          controller:
            protocol: PLAINTEXT
          interbroker:
            protocol: PLAINTEXT
          external:
            protocol: PLAINTEXT
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true