apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: admin
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: kafka
    targetRevision: 31.2.0
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true