apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: admin
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: grafana-loki
    targetRevision: 5.0.0
    helm:
      values: |
        queryFrontend:
          resources:
            limits:
              cpu: "4000m"
              memory: "4Gi"
            requests:
              cpu: "250m"
              memory: "256Mi"
        querier:
          resources:
            limits:
              cpu: "4000m"
              memory: "4Gi"
            requests:
              cpu: "250m"
              memory: "256Mi"
        grafanaalloy:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 