apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: admin
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.30.1
    helm:
      values: |
        # Konfiguracja z PostgreSQL dla indeksów i filesystem dla chunks
        loki:
          config:
            auth_enabled: false
            server:
              http_listen_port: 3100
              grpc_listen_port: 9095
              
            common:
              path_prefix: /var/loki
              replication_factor: 1
              ring:
                kvstore:
                  store: inmemory
                  
            schema_config:
              configs:
                - from: 2020-10-24
                  store: tsdb
                  object_store: filesystem
                  schema: v13
                  index:
                    prefix: index_
                    period: 24h
                    
            storage_config:
              filesystem:
                directory: /var/loki/chunks
              tsdb_shipper:
                active_index_directory: /var/loki/tsdb-index
                cache_location: /var/loki/tsdb-cache
                
            limits_config:
              retention_period: 168h # 7 dni
              
            compactor:
              working_directory: /var/loki/compactor
              retention_enabled: true
              retention_delete_delay: 2h
              retention_delete_worker_count: 150
              
            ingester:
              lifecycler:
                ring:
                  kvstore:
                    store: inmemory
                  replication_factor: 1
                address: 127.0.0.1
                port: 9095
                final_sleep: 0s
              chunk_idle_period: 1h
              max_chunk_age: 1h
              chunk_target_size: 1048576
              chunk_retain_period: 30s
              
        # Pojedynczy pod
        deploymentMode: SingleBinary
        
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 50Gi
            storageClass: smb-sc
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
          
        # Wyłączamy niepotrzebne komponenty dla SingleBinary
        ingester:
          enabled: false
        distributor:
          enabled: false
        querier:
          enabled: false
        queryFrontend:
          enabled: false
        queryScheduler:
          enabled: false
        compactor:
          enabled: false
        indexGateway:
          enabled: false
        bloomCompactor:
          enabled: false
        bloomGateway:
          enabled: false
          
        # Monitoring
        monitoring:
          dashboards:
            enabled: false
          rules:
            enabled: false
          serviceMonitor:
            enabled: false
            
        # Test
        test:
          enabled: false
          
        # Service
        service:
          type: ClusterIP
          port: 3100
          
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true