apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: admin
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.30.0
    helm:
      values: |
        # SingleBinary deployment mode
        deploymentMode: SingleBinary
        
        # Loki configuration
        loki:
          auth_enabled: false
          
          # Storage configuration
          storage:
            type: filesystem
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin
            filesystem:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
          
          # Schema configuration
          schemaConfig:
            configs:
              - from: 2020-10-24
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          
          # Storage configuration
          storage_config:
            filesystem:
              directory: /var/loki/chunks
            tsdb_shipper:
              active_index_directory: /var/loki/tsdb-index
              cache_location: /var/loki/tsdb-cache
              
          # Common configuration
          commonConfig:
            path_prefix: /var/loki
            replication_factor: 1
            ring:
              kvstore:
                store: inmemory
                
          # Limits configuration
          limits_config:
            retention_period: 168h
            
          # Server configuration  
          server:
            http_listen_port: 3100
            grpc_listen_port: 9095
            
          # Ingester configuration
          ingester:
            lifecycler:
              ring:
                kvstore:
                  store: inmemory
                replication_factor: 1
              address: 127.0.0.1
              port: 9095
              final_sleep: 0s
            chunk_idle_period: 1h
            max_chunk_age: 1h
            chunk_target_size: 1048576
            chunk_retain_period: 30s
            
          # Compactor configuration
          compactor:
            working_directory: /var/loki/compactor
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
        
        # SingleBinary specific configuration
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 50Gi
            storageClass: smb-sc
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
        
        # Disable other components (not needed for SingleBinary)
        ingester:
          replicas: 0
        distributor:
          replicas: 0
        querier:
          replicas: 0
        queryFrontend:
          replicas: 0
        queryScheduler:
          replicas: 0
        compactor:
          replicas: 0
        indexGateway:
          replicas: 0
        bloomCompactor:
          replicas: 0
        bloomGateway:
          replicas: 0
        ruler:
          enabled: false
        gateway:
          enabled: false
        
        # Monitoring
        monitoring:
          dashboards:
            enabled: false
          rules:
            enabled: false
          serviceMonitor:
            enabled: false
        
        # Test
        test:
          enabled: false
          
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true