apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: admin
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 14.8.2
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true