apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: admin
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: minio
    targetRevision: 15.0.7
    helm:
      values: |
        persistence:
          storageClass: local-storage
          existingClaim: minio-pvc
        resources:
          limits:
            cpu: "2000m"
            ephemeral-storage: 2Gi
            memory: "1Gi"
          requests:
            cpu: "250m"
            ephemeral-storage: 50Mi
            memory: "256Mi"
        ingress:
          enabled: true
          annotations:
            # Usunięte wszystkie adnotacje związane z HTTPS/TLS
            traefik.ingress.kubernetes.io/router.entrypoints: "web"
          hostname: minio.iwal.duckdns.org
          path: /
          pathType: Prefix
          tls: false  # Wyłączone TLS
          # Usunięte extraTls
      
        apiIngress:
          enabled: true
          annotations:
            # Usunięte wszystkie adnotacje związane z HTTPS/TLS
            traefik.ingress.kubernetes.io/router.entrypoints: "web"
          hostname: minioapi.iwal.duckdns.org
          tls: false  # Wyłączone TLS
          # Usunięte extraTls
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true