apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: admin
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 14.8.2
    helm:
      values: |
        resources:
          limits:
            cpu: "2000m"
            ephemeral-storage: 2Gi
            memory: "1Gi"
          requests:
            cpu: "250m"
            ephemeral-storage: 50Mi
            memory: "256Mi"
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.tls.certresolver: "duckdnsresolver"
          hostname: minio.iwal.duckdns.org
          path: /
          pathType: Prefix
          tls: true
          extraTls:
            - hosts:
              - minio.iwal.duckdns.org
              secretName: minio-cert
      
        apiIngress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.tls.certresolver: "duckdnsresolver"
          hostname: minioapi.iwal.duckdns.org
          tls: true
          extraTls:
            - hosts:
              - minioapi.iwal.duckdns.org
              secretName: minioapi-cert
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true