apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nessie
  namespace: admin
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: nessie
    targetRevision: 1.1.2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true