apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2
  namespace: admin
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 18.2.0
    helm:
      values: |
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: iwal.duckdns.org
          path: /
          pathType: ImplementationSpecific
          tls: false
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true