apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: admin
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: postgresql
    targetRevision: 16.7.12
    helm:
      values: |
        auth:
          postgresPassword: "admin123"
          database: "appdb"
        primary:
          persistence:
            enabled: true
            storageClass: "smb-sc"
            size: 2Ti
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          podSecurityContext:
            enabled: true
            fsGroup: 1001
            runAsUser: 1001
            runAsGroup: 1001
          containerSecurityContext:
            enabled: true
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
        metrics:
          enabled: true
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
        serviceMonitor:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 