apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: admin
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: postgresql
    targetRevision: 16.7.12
    helm:
      values: |
        auth:
          existingSecret: "postgresql-secret"
        image:
          debug: true
        global:
          defaultStorageClass: smb-sc
        primary:
          persistence:
            enabled: true
            size: 2Ti
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "256Mi"
        primary:
          service:
            type: NodePort
            nodePorts:
              postgresql: 30001
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 