apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino-gateway
  namespace: admin
spec:
  project: default
  source:
    repoURL: https://trinodb.github.io/charts
    chart: trino-gateway
    targetRevision: 1.13.0
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true