apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: admin
spec:
  project: default
  source:
    repoURL: https://trinodb.github.io/charts
    chart: trino
    targetRevision: 1.35.0
    helm:
      values: |
        catalogs:
          memory-test: |
            connector.name=memory
            memory.max-data-per-node=128MB

          iceberg_minio: |
            connector.name=iceberg
            iceberg.catalog.type=nessie
            iceberg.nessie-catalog.uri=http://nessie.default.svc.cluster.local:19120/api/v2
            iceberg.nessie-catalog.default-warehouse-dir=/tmp

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
