apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: admin
spec:
  project: default
  source:
    repoURL: https://trinodb.github.io/charts
    chart: trino
    targetRevision: 1.35.0
    helm:
      values: |
        catalogs:
          memory-test: |
            connector.name=memory
            memory.max-data-per-node=128MB

          iceberg-minio: |
            connector.name=iceberg
            catalog.type=nessie
            nessie-catalog.uri=http://nessie.default.svc.cluster.local:19120/api/v2
            nessie-catalog.default-warehouse-dir=/tmp
            warehouse=s3a://iceberg-data/
            s3.endpoint=http://minio.admin.svc.cluster.local:9000
            s3.region=us-east-1
            s3.path-style-access=true

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
