apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scraper
  namespace: admin
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/femex/yet-another-scraper-helm
    targetRevision: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
