apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scraper
  namespace: admin
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/femex
    chart: yet-another-scraper-helm
    targetRevision: "*-0"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
